#!/bin/bash

# Run the Spring Boot application with local profile

echo "Step 5: Starting application..."
echo ""
echo "=========================================="
echo "Application Running!"
echo "=========================================="
echo ""
echo "API URL: http://localhost:8080"
echo "Swagger UI: http://localhost:8080/swagger-ui.html"
echo ""
echo "Services:"
echo "  - Application: http://localhost:8080"
echo "  - PostgreSQL: localhost:5432"
echo "  - RabbitMQ: localhost:5672"
echo "  - LocalStack: localhost:4566"
echo ""
echo "Quick Test Commands:"
echo ""
echo "1. Health Check:"
echo "   curl http://localhost:8080/actuator/health"
echo ""
echo "2. Login as Admin (auto-created for local):"
echo "   curl -X POST http://localhost:8080/auth/login \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"username\":\"admin\",\"password\":\"Admin123!\"}'"
echo ""
echo "3. Register New User:"
echo "   curl -X POST http://localhost:8080/auth/register \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"username\":\"user1\",\"password\":\"Pass123!\",\"roleName\":\"USER\"}'"
echo ""
echo "4. Create Card (use token from login):"
echo "   TOKEN=<jwt-token>"
echo "   curl -X POST http://localhost:8080/api/cards \\"
echo "     -H \"Authorization: Bearer \$TOKEN\" \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"cardNumber\":\"4456897999999999\"}'"
echo ""
echo "To stop: Press Ctrl+C"
echo "=========================================="
echo ""

./gradlew bootRun --args='--spring.profiles.active=local'

